import { Request, Response, Router } from "express"
import { requireAuth } from "../auth/middleware"
import {
  getReceiptWithDetails,
  listReceiptsByClientId,
  listReceiptsByPolicyId,
} from "../repositories"
import { parseId } from "./helpers"
import { idParam } from "./schemas"

export const receiptsRouter = Router()

// Receipts are read-only records generated by recording a payment. Filter by
// clientId or policyId.
receiptsRouter.get("/receipts", requireAuth, async (req: Request, res: Response) => {
  if (typeof req.query.clientId === "string") {
    const clientId = idParam.safeParse(req.query.clientId)
    if (!clientId.success) {
      res.status(400).json({ error: "Invalid clientId" })
      return
    }
    res.json(await listReceiptsByClientId(clientId.data))
    return
  }
  if (typeof req.query.policyId === "string") {
    const policyId = idParam.safeParse(req.query.policyId)
    if (!policyId.success) {
      res.status(400).json({ error: "Invalid policyId" })
      return
    }
    res.json(await listReceiptsByPolicyId(policyId.data))
    return
  }
  res.status(400).json({ error: "Provide a clientId or policyId" })
})

receiptsRouter.get("/receipts/:id", requireAuth, async (req: Request, res: Response) => {
  const id = parseId(req.params.id, res)
  if (id === undefined) return

  const receipt = await getReceiptWithDetails(id)
  if (!receipt) {
    res.status(404).json({ error: "Receipt not found" })
    return
  }
  res.json(receipt)
})
